name: Feature Request
description: Want a feature? Ask; we don't bite!
labels: 'enhancement'
body:
  - type: markdown
    attributes:
      value: |
        ## Self Check
        - Try searching existing [GitHub Issues](https://github.com/TheTechRobo/openclassroom/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) (open or closed) and Discussions for similar issues.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the feature
      description: A clear description of what the feature is.
      placeholder: What if we could add USB support?!
  - type: textarea
    validations:
      required: true
    attributes:
      label: Does this fix a problem? If so, specify.
      placeholder: Many people don't have an SD card.
  - type: textarea
    attributes:
      label: Did you consider other alternatives?
      description: If so, specify
  - type: textarea
    attributes:
      label: Screenshots and recordings
      description: |
        If applicable, add screenshots or videos to help explain your problem. (You might edit them to show what you want, or just explain where the feature should go and any problems behind the existing behaviour!) (Videos should be as short as possible! Avoid watermarks too.)
  - type: input
    validations:
    attributes:
      label: Additional context
